sudo: required
language: python
services:
- docker

env:
 - IMAGE=dind
 - VERSION="1.0.0"

script:
- docker build -t $DOCKER_USERNAME/$IMAGE:$VERSION .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/$IMAGE:$VERSION