sudo: required
language: python
services:
- docker

script:
- docker build -t $DOCKER_USERNAME/$IMAGE:$VERSION .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/$IMAGE:$VERSION
- docker push $DOCKER_USERNAME/$IMAGE:latest